root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "ixod"
  cmd = "go install ./cli/ixod"
  delay = 1000
  exclude_dir = ["assets", "tmp", "testdata", "node_modules"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "APP_USER=root /go/bin/ixod start --pruning 'nothing' --log_level='warn'"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "500ms"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
