package types

import (
	sdkErrors "github.com/cosmos/cosmos-sdk/types/errors"
)

var (
	DefaultCodespace = ModuleName

	ErrArgumentCannotBeEmpty                = sdkErrors.Register(DefaultCodespace, 2, " argument cannot be empty")
	ErrArgumentCannotBeNegative             = sdkErrors.Register(DefaultCodespace, 3, "argument cannot be negative")
	ErrArgumentMustBePositive               = sdkErrors.Register(DefaultCodespace, 4, "argument must be a positive value")
	ErrArgumentMustBeInteger                = sdkErrors.Register(DefaultCodespace, 5, "argument must be an integer value")
	ErrArgumentMustBeBetween                = sdkErrors.Register(DefaultCodespace, 6, "argument must be between")
	ErrFunctionParameterMissingOrNonFloat   = sdkErrors.Register(DefaultCodespace, 7, "parameter is missing or is not a float")
	ErrArgumentMissingOrNonFloat            = sdkErrors.Register(DefaultCodespace, 8, "argument is missing or is not a float")
	ErrArgumentMissingOrNonUInteger         = sdkErrors.Register(DefaultCodespace, 9, " argument is missing or is not an unsigned integer")
	ErrArgumentMissingOrNonBoolean          = sdkErrors.Register(DefaultCodespace, 10, "argument is missing or is not true or false")
	ErrIncorrectNumberOfReserveTokens       = sdkErrors.Register(DefaultCodespace, 11, "Incorrect number of reserve tokens")
	ErrIncorrectNumberOfFunctionParameters  = sdkErrors.Register(DefaultCodespace, 12, "Incorrect number of function parameters")
	ErrBondDoesNotExist                     = sdkErrors.Register(DefaultCodespace, 13, "Bond  does not exist")
	ErrBondAlreadyExists                    = sdkErrors.Register(DefaultCodespace, 14, "Bond  already exists")
	ErrBondTokenIsTaken                     = sdkErrors.Register(DefaultCodespace, 15, "Bond token is taken")
	ErrBondDoesNotAllowSelling              = sdkErrors.Register(DefaultCodespace, 16, "Bond does not allow selling at the moment")
	ErrDidNotEditAnything                   = sdkErrors.Register(DefaultCodespace, 17, "Bond does not allow selling at the moment")
	ErrFromAndToCannotBeTheSameToken        = sdkErrors.Register(DefaultCodespace, 18, "From and To tokens cannot be the same token")
	ErrDuplicateReserveToken                = sdkErrors.Register(DefaultCodespace, 19, "Cannot have duplicate tokens in reserve tokens")
	ErrInvalidStateForAction                = sdkErrors.Register(DefaultCodespace, 20, "Cannot perform that action at the current state")
	ErrUnrecognizedFunctionType             = sdkErrors.Register(DefaultCodespace, 21, "Unrecognized function type")
	ErrInvalidFunctionParameter             = sdkErrors.Register(DefaultCodespace, 22, "Invalid function parameter")
	ErrFunctionNotAvailableForFunctionType  = sdkErrors.Register(DefaultCodespace, 23, "Function is not available for the function type")
	ErrCannotMakeZeroOutcomePayment         = sdkErrors.Register(DefaultCodespace, 24, "Cannot make outcome payment because outcome payment is set to nil")
	ErrFunctionRequiresNonZeroCurrentSupply = sdkErrors.Register(DefaultCodespace, 25, "Function requires the current supply to be non zero")
	ErrTokenIsNotAValidReserveToken         = sdkErrors.Register(DefaultCodespace, 26, "Token is not a valid reserve token")
	ErrMaxSupplyDenomDoesNotMatchTokenDenom = sdkErrors.Register(DefaultCodespace, 27, "Token is not a valid reserve token")
	ErrBondTokenCannotAlsoBeReserveToken    = sdkErrors.Register(DefaultCodespace, 28, "Token cannot also be a reserve token")
	ErrBondTokenCannotBeStakingToken        = sdkErrors.Register(DefaultCodespace, 29, "Bond token cannot be staking token")
	ErrReserveDenomsMismatch                = sdkErrors.Register(DefaultCodespace, 30, "Denoms in do not match reserve denoms")
	ErrInvalidCoinDenomination              = sdkErrors.Register(DefaultCodespace, 31, "Invalid coin denomination ")
	ErrCannotMintMoreThanMaxSupply          = sdkErrors.Register(DefaultCodespace, 32, "Cannot mint more tokens than the max supply")
	ErrCannotBurnMoreThanSupply             = sdkErrors.Register(DefaultCodespace, 33, "Cannot burn more tokens than the current supply")
	ErrMaxPriceExceeded                     = sdkErrors.Register(DefaultCodespace, 34, "Actual prices  exceed max prices ")
	ErrSwapAmountTooSmallToGiveAnyReturn    = sdkErrors.Register(DefaultCodespace, 35, "swap amount too small to give any return")
	ErrSwapAmountCausesReserveDepletion     = sdkErrors.Register(DefaultCodespace, 36, "swap amount too large and causes  reserve to be depleted")
	ErrOrderQuantityLimitExceeded           = sdkErrors.Register(DefaultCodespace, 37, "Order quantity limits exceeded")
	ErrValuesViolateSanityRate              = sdkErrors.Register(DefaultCodespace, 38, "Values violate sanity rate")
	ErrFeesCannotBeOrExceed100Percent       = sdkErrors.Register(DefaultCodespace, 39, "Sum of fees is or exceeds 100 percent")
	ErrNoBondTokensOwned                    = sdkErrors.Register(DefaultCodespace, 40, "No bond tokens of this bond are owned")
	ErrInsufficientReserveToBuy             = sdkErrors.Register(DefaultCodespace, 41, "Insufficient reserve was supplied to perform buy order")
	ErrInternal                             = sdkErrors.Register(DefaultCodespace, 42, "internal error")
	ErrBondTokenDoesNotMatchBond            = sdkErrors.Register(DefaultCodespace, 43, "bond doesn't match")
)
