jobs:
  
  test-build:
    name: Run ${{ matrix.test }} tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build:
          - build-command: docker build -t ${{ docker.image }} .
            artifact: app
            os: ubuntu-latests
            
          - build-command: docker build -t ${{ docker.image }} .
            artifact: app
            os: ubuntu-latests
          
        include:
          - test: unit
            command: npm test

          - test: integration
            command: npm test
    steps:
      - run: echo "All Good"