name: Publish Release

on: 
  push:
    branches:
      - "devel/ops-upgrade"

jobs:
  # test:
  
  # create-prerelease:
   
  publish-github-prerelease:
    name: Publish Github Release
    runs-on: ubuntu-latest

    # needs:
      # - build-package
      # - upload-release-artifacts
    # outputs:
    #   version: ${{ steps.release.outputs.tag_name }}
    #   changelog: ${{ steps.release.outputs.body }}
    #   changelog-url: ${{ steps.release.outputs.html_url }}
    steps:
      - name: Git Version
        uses: codacy/git-version@2.2.0
        
      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: '2.11.7-alpha3'
          version-fragment: 'feature'
          
      - name: Publish Pre Release
        id: pre-release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: prerelease-config.yaml
          version: "1.2.3"
          publish: true
          commitish: ${{ github.sha }}

      - name: Publish Stable Release
        id: stable-release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-config.yaml
          publish: false
          commitish: ${{ github.sha }}

#udhui