name: Request Environment Destruction

on:
  workflow_call:
    inputs: {}
    secrets: 
      token:
        required: true
        description: "GitHub token"
      pa-token:
        required: true
        description: "Personal access token"

jobs:
  provision-environment:
    name: Destroy Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          repository: ${{ env.SYSTEM_REPOSITORY }}
          ref: 'release/v0'
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          
      - if: ${{ false }}
        run: echo "mage destroy xxx"

      - run: echo "mage install xxx"
      
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: example-patches
          delete-branch: true
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: peter-evans
          reviewers: peter-evans
          team-reviewers: |
            owners
            maintainers
          milestone: 1
          draft: false