name: Request Environment

on:
  workflow_call:
    inputs: {}
    secrets: 
      token:
        required: true
        description: "GitHub token"
      pa-token:
        required: true
        description: "Personal access token"
        
env:
  SYSTEM_REPOSITORY: ${{ secrets.PROJECT_SYSTEM }}
  SYSTEM_REPOSITORY_PATH: ${{ format('k8s-system') }}

jobs:
  request-environment:
    name: Provision Environment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '../k8s-system'
    steps:
      - uses: actions/checkout@v1
        with:
          repository: ${{ env.SYSTEM_REPOSITORY }}
          ref: 'release/v1'
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          path: ${{ env.SYSTEM_REPOSITORY_PATH }}

      - if: ${{ false }}
        run: echo "mage provission xxx"

      - run: echo "mage install xxx"

      # - run: echo "hi" > temp.txt
      #   working-directory: ../k8s-system
      # - run: /usr/bin/git config --local --get remote.origin.url
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        id: create-pull-request
        with:
          path: '../k8s-system'
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: 'requests/provision-jira-33'
          delete-branch: true
          title: 'Provission jira-33'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          draft: false

      - name: Enable Pull Request Automerge
        if: steps.create-pull-request.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.pa-token }}
          pull-request-number: ${{ steps.create-pull-request.outputs.pull-request-number }}
          merge-method: squash
      # - uses: convictional/trigger-workflow-and-wait@v1.3.0
      #   with:
      #     owner: keithconvictional
      #     repo: myrepo
      #     github_token: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
      #     workflow_file_name: main.yml
      #     ref: release-branch
      #     wait_interval: 10
      #     inputs: '{}'
      #     propagate_failure: false
      #     trigger_workflow: true
      #     wait_workflow: true

  # notify-jira:
  #   name: Notify Jira
  #   runs-on: ubuntu-latest
  #   needs: [check-prerequisites, request-environment]
  #   steps:
  #     - name: Login
  #       uses: atlassian/gajira-login@master
  #       env:
  #         JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
  #         JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
  #         JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
  #     - name: Comment on issue
  #     - uses: atlassian/gajira-comment@master
  #       with:
  #         issue: INC-2
  #         comment: |
  #           ${{ github.event.pusher.name }} pushed to repository: ${{ github.event.repository.full_name }}
            
  # notify-githuh:
  #   name: Notify Github
  #   runs-on: ubuntu-latest
  #   needs: [check-prerequisites, request-environment]
  #   steps:
  #     - run: echo "github"
        
  # notify-slack:
  #   name: Notify Slack
  #   runs-on: ubuntu-latest
  #   needs: [check-prerequisites, request-environment]
  #   steps:
  #     - run: echo "slack"