on:
  push:
    branches: main

  
jobs:
  test:
  
  create-prerelease:
   
  publish-github-release:
    name: Publish Github Release
    runs-on: ubuntu-latest
    needs:
      - build-package
      - upload-release-artifacts
    outputs:
      version: ${{ steps.release.outputs.tag_name }}
      changelog: ${{ steps.release.outputs.body }}
      changelog-url: ${{ steps.release.outputs.html_url }}
    steps:
      - name: Publish Release
        id: release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          config-name: ${{ env.release-config }}
          publish: true
          commitish: ${{ github.sha }}