// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ixo/claims/v1beta1/authz.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	types1 "github.com/cosmos/cosmos-sdk/x/bank/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AuthorizationType defines the types of claim authorizations that can be
// created
type CreateClaimAuthorizationType int32

const (
	CreateClaimAuthorizationType_ALL      CreateClaimAuthorizationType = 0
	CreateClaimAuthorizationType_SUBMIT   CreateClaimAuthorizationType = 1
	CreateClaimAuthorizationType_EVALUATE CreateClaimAuthorizationType = 2
)

var CreateClaimAuthorizationType_name = map[int32]string{
	0: "ALL",
	1: "SUBMIT",
	2: "EVALUATE",
}

var CreateClaimAuthorizationType_value = map[string]int32{
	"ALL":      0,
	"SUBMIT":   1,
	"EVALUATE": 2,
}

func (x CreateClaimAuthorizationType) String() string {
	return proto.EnumName(CreateClaimAuthorizationType_name, int32(x))
}

func (CreateClaimAuthorizationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f4b7f6c531e101a6, []int{0}
}

type SubmitClaimAuthorization struct {
	// address of admin (entity admin module account)
	Admin       string                    `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	Constraints []*SubmitClaimConstraints `protobuf:"bytes,2,rep,name=constraints,proto3" json:"constraints,omitempty"`
}

func (m *SubmitClaimAuthorization) Reset()         { *m = SubmitClaimAuthorization{} }
func (m *SubmitClaimAuthorization) String() string { return proto.CompactTextString(m) }
func (*SubmitClaimAuthorization) ProtoMessage()    {}
func (*SubmitClaimAuthorization) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4b7f6c531e101a6, []int{0}
}
func (m *SubmitClaimAuthorization) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubmitClaimAuthorization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubmitClaimAuthorization.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubmitClaimAuthorization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitClaimAuthorization.Merge(m, src)
}
func (m *SubmitClaimAuthorization) XXX_Size() int {
	return m.Size()
}
func (m *SubmitClaimAuthorization) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitClaimAuthorization.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitClaimAuthorization proto.InternalMessageInfo

func (m *SubmitClaimAuthorization) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *SubmitClaimAuthorization) GetConstraints() []*SubmitClaimConstraints {
	if m != nil {
		return m.Constraints
	}
	return nil
}

type SubmitClaimConstraints struct {
	// collection_id indicates to which Collection this claim belongs
	CollectionId string `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	AgentQuota   uint64 `protobuf:"varint,2,opt,name=agent_quota,json=agentQuota,proto3" json:"agent_quota,omitempty"`
	// custom max_amount allowed to be specified by service agent for claim
	// approval, if empty then no custom amount is allowed, and default payments
	// from Collection payments are used
	MaxAmount github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=max_amount,json=maxAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"max_amount"`
	// custom max_cw20_payment allowed to be specified by service agent for claim
	// approval, if empty then no custom amount is allowed, and default payments
	// from Collection payments are used
	MaxCw20Payment []*CW20Payment `protobuf:"bytes,4,rep,name=max_cw20_payment,json=maxCw20Payment,proto3" json:"max_cw20_payment,omitempty"`
	// intent_duration_ns is the duration for which the intent is active, after
	// which it will expire (in nanoseconds)
	IntentDurationNs time.Duration `protobuf:"bytes,5,opt,name=intent_duration_ns,json=intentDurationNs,proto3,stdduration" json:"intent_duration_ns"`
	// custom max_cw1155_payment allowed to be specified by service agent for
	// claim approval, if empty then no custom amount is allowed, and default
	// payments from Collection payments are used
	MaxCw1155Payment []*CW1155Payment `protobuf:"bytes,6,rep,name=max_cw1155_payment,json=maxCw1155Payment,proto3" json:"max_cw1155_payment,omitempty"`
}

func (m *SubmitClaimConstraints) Reset()         { *m = SubmitClaimConstraints{} }
func (m *SubmitClaimConstraints) String() string { return proto.CompactTextString(m) }
func (*SubmitClaimConstraints) ProtoMessage()    {}
func (*SubmitClaimConstraints) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4b7f6c531e101a6, []int{1}
}
func (m *SubmitClaimConstraints) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubmitClaimConstraints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubmitClaimConstraints.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubmitClaimConstraints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitClaimConstraints.Merge(m, src)
}
func (m *SubmitClaimConstraints) XXX_Size() int {
	return m.Size()
}
func (m *SubmitClaimConstraints) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitClaimConstraints.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitClaimConstraints proto.InternalMessageInfo

func (m *SubmitClaimConstraints) GetCollectionId() string {
	if m != nil {
		return m.CollectionId
	}
	return ""
}

func (m *SubmitClaimConstraints) GetAgentQuota() uint64 {
	if m != nil {
		return m.AgentQuota
	}
	return 0
}

func (m *SubmitClaimConstraints) GetMaxAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.MaxAmount
	}
	return nil
}

func (m *SubmitClaimConstraints) GetMaxCw20Payment() []*CW20Payment {
	if m != nil {
		return m.MaxCw20Payment
	}
	return nil
}

func (m *SubmitClaimConstraints) GetIntentDurationNs() time.Duration {
	if m != nil {
		return m.IntentDurationNs
	}
	return 0
}

func (m *SubmitClaimConstraints) GetMaxCw1155Payment() []*CW1155Payment {
	if m != nil {
		return m.MaxCw1155Payment
	}
	return nil
}

type EvaluateClaimAuthorization struct {
	// address of admin (entity admin module account)
	Admin       string                      `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	Constraints []*EvaluateClaimConstraints `protobuf:"bytes,2,rep,name=constraints,proto3" json:"constraints,omitempty"`
}

func (m *EvaluateClaimAuthorization) Reset()         { *m = EvaluateClaimAuthorization{} }
func (m *EvaluateClaimAuthorization) String() string { return proto.CompactTextString(m) }
func (*EvaluateClaimAuthorization) ProtoMessage()    {}
func (*EvaluateClaimAuthorization) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4b7f6c531e101a6, []int{2}
}
func (m *EvaluateClaimAuthorization) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EvaluateClaimAuthorization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EvaluateClaimAuthorization.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EvaluateClaimAuthorization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvaluateClaimAuthorization.Merge(m, src)
}
func (m *EvaluateClaimAuthorization) XXX_Size() int {
	return m.Size()
}
func (m *EvaluateClaimAuthorization) XXX_DiscardUnknown() {
	xxx_messageInfo_EvaluateClaimAuthorization.DiscardUnknown(m)
}

var xxx_messageInfo_EvaluateClaimAuthorization proto.InternalMessageInfo

func (m *EvaluateClaimAuthorization) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *EvaluateClaimAuthorization) GetConstraints() []*EvaluateClaimConstraints {
	if m != nil {
		return m.Constraints
	}
	return nil
}

type EvaluateClaimConstraints struct {
	// collection_id indicates to which Collection this claim belongs
	CollectionId string `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	// either collection_id or claim_ids is needed
	ClaimIds   []string `protobuf:"bytes,2,rep,name=claim_ids,json=claimIds,proto3" json:"claim_ids,omitempty"`
	AgentQuota uint64   `protobuf:"varint,3,opt,name=agent_quota,json=agentQuota,proto3" json:"agent_quota,omitempty"`
	// if null then no before_date validation done
	BeforeDate *time.Time `protobuf:"bytes,4,opt,name=before_date,json=beforeDate,proto3,stdtime" json:"before_date,omitempty"`
	// max custom amount evaluator can change, if empty then no custom amount is
	// allowed, and default payments from Collection payments are used
	MaxCustomAmount github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,10,rep,name=max_custom_amount,json=maxCustomAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"max_custom_amount"`
	// max custom cw20 payment evaluator can change, if empty then no custom
	// amount is allowed, and default payments from Collection payments are used
	MaxCustomCw20Payment []*CW20Payment `protobuf:"bytes,11,rep,name=max_custom_cw20_payment,json=maxCustomCw20Payment,proto3" json:"max_custom_cw20_payment,omitempty"`
	// custom max_cw1155_payment evaluator can change, if empty then no custom
	// amount is allowed, and default payments from Collection payments are used
	MaxCustomCw1155Payment []*CW1155Payment `protobuf:"bytes,12,rep,name=max_custom_cw1155_payment,json=maxCustomCw1155Payment,proto3" json:"max_custom_cw1155_payment,omitempty"`
}

func (m *EvaluateClaimConstraints) Reset()         { *m = EvaluateClaimConstraints{} }
func (m *EvaluateClaimConstraints) String() string { return proto.CompactTextString(m) }
func (*EvaluateClaimConstraints) ProtoMessage()    {}
func (*EvaluateClaimConstraints) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4b7f6c531e101a6, []int{3}
}
func (m *EvaluateClaimConstraints) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EvaluateClaimConstraints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EvaluateClaimConstraints.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EvaluateClaimConstraints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvaluateClaimConstraints.Merge(m, src)
}
func (m *EvaluateClaimConstraints) XXX_Size() int {
	return m.Size()
}
func (m *EvaluateClaimConstraints) XXX_DiscardUnknown() {
	xxx_messageInfo_EvaluateClaimConstraints.DiscardUnknown(m)
}

var xxx_messageInfo_EvaluateClaimConstraints proto.InternalMessageInfo

func (m *EvaluateClaimConstraints) GetCollectionId() string {
	if m != nil {
		return m.CollectionId
	}
	return ""
}

func (m *EvaluateClaimConstraints) GetClaimIds() []string {
	if m != nil {
		return m.ClaimIds
	}
	return nil
}

func (m *EvaluateClaimConstraints) GetAgentQuota() uint64 {
	if m != nil {
		return m.AgentQuota
	}
	return 0
}

func (m *EvaluateClaimConstraints) GetBeforeDate() *time.Time {
	if m != nil {
		return m.BeforeDate
	}
	return nil
}

func (m *EvaluateClaimConstraints) GetMaxCustomAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.MaxCustomAmount
	}
	return nil
}

func (m *EvaluateClaimConstraints) GetMaxCustomCw20Payment() []*CW20Payment {
	if m != nil {
		return m.MaxCustomCw20Payment
	}
	return nil
}

func (m *EvaluateClaimConstraints) GetMaxCustomCw1155Payment() []*CW1155Payment {
	if m != nil {
		return m.MaxCustomCw1155Payment
	}
	return nil
}

type WithdrawPaymentAuthorization struct {
	// address of admin
	Admin       string                        `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	Constraints []*WithdrawPaymentConstraints `protobuf:"bytes,2,rep,name=constraints,proto3" json:"constraints,omitempty"`
}

func (m *WithdrawPaymentAuthorization) Reset()         { *m = WithdrawPaymentAuthorization{} }
func (m *WithdrawPaymentAuthorization) String() string { return proto.CompactTextString(m) }
func (*WithdrawPaymentAuthorization) ProtoMessage()    {}
func (*WithdrawPaymentAuthorization) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4b7f6c531e101a6, []int{4}
}
func (m *WithdrawPaymentAuthorization) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WithdrawPaymentAuthorization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WithdrawPaymentAuthorization.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WithdrawPaymentAuthorization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawPaymentAuthorization.Merge(m, src)
}
func (m *WithdrawPaymentAuthorization) XXX_Size() int {
	return m.Size()
}
func (m *WithdrawPaymentAuthorization) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawPaymentAuthorization.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawPaymentAuthorization proto.InternalMessageInfo

func (m *WithdrawPaymentAuthorization) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *WithdrawPaymentAuthorization) GetConstraints() []*WithdrawPaymentConstraints {
	if m != nil {
		return m.Constraints
	}
	return nil
}

type WithdrawPaymentConstraints struct {
	// claim_id the withdrawal is for
	ClaimId string `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	// Inputs to the multisend tx to run to withdraw payment
	Inputs []types1.Input `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs"`
	// Outputs for the multisend tx to run to withdraw payment
	Outputs []types1.Output `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs"`
	// payment type to keep track what payment is for and mark claim payment
	// accordingly
	PaymentType PaymentType `protobuf:"varint,4,opt,name=payment_type,json=paymentType,proto3,enum=ixo.claims.v1beta1.PaymentType" json:"payment_type,omitempty"`
	// if empty(nil) then no contract payment
	Contract_1155Payment *Contract1155Payment `protobuf:"bytes,5,opt,name=contract_1155_payment,json=contract1155Payment,proto3" json:"contract_1155_payment,omitempty"` // Deprecated: Do not use.
	// for contract payment
	ToAddress string `protobuf:"bytes,6,opt,name=toAddress,proto3" json:"toAddress,omitempty"`
	// for contract payment
	FromAddress string `protobuf:"bytes,7,opt,name=fromAddress,proto3" json:"fromAddress,omitempty"`
	// date that grantee can execute authorization, calculated from created date
	// plus the timeout on Collection payments, if null then none
	ReleaseDate *time.Time `protobuf:"bytes,8,opt,name=release_date,json=releaseDate,proto3,stdtime" json:"release_date,omitempty"`
	// cw20 payments, can be empty or multiple
	Cw20Payment []*CW20Payment `protobuf:"bytes,9,rep,name=cw20_payment,json=cw20Payment,proto3" json:"cw20_payment,omitempty"`
	// custom cw1155 payments, can be empty or multiple
	Cw1155Payment []*CW1155Payment `protobuf:"bytes,10,rep,name=cw1155_payment,json=cw1155Payment,proto3" json:"cw1155_payment,omitempty"`
}

func (m *WithdrawPaymentConstraints) Reset()         { *m = WithdrawPaymentConstraints{} }
func (m *WithdrawPaymentConstraints) String() string { return proto.CompactTextString(m) }
func (*WithdrawPaymentConstraints) ProtoMessage()    {}
func (*WithdrawPaymentConstraints) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4b7f6c531e101a6, []int{5}
}
func (m *WithdrawPaymentConstraints) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WithdrawPaymentConstraints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WithdrawPaymentConstraints.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WithdrawPaymentConstraints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawPaymentConstraints.Merge(m, src)
}
func (m *WithdrawPaymentConstraints) XXX_Size() int {
	return m.Size()
}
func (m *WithdrawPaymentConstraints) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawPaymentConstraints.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawPaymentConstraints proto.InternalMessageInfo

func (m *WithdrawPaymentConstraints) GetClaimId() string {
	if m != nil {
		return m.ClaimId
	}
	return ""
}

func (m *WithdrawPaymentConstraints) GetInputs() []types1.Input {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *WithdrawPaymentConstraints) GetOutputs() []types1.Output {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *WithdrawPaymentConstraints) GetPaymentType() PaymentType {
	if m != nil {
		return m.PaymentType
	}
	return PaymentType_submission
}

// Deprecated: Do not use.
func (m *WithdrawPaymentConstraints) GetContract_1155Payment() *Contract1155Payment {
	if m != nil {
		return m.Contract_1155Payment
	}
	return nil
}

func (m *WithdrawPaymentConstraints) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *WithdrawPaymentConstraints) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *WithdrawPaymentConstraints) GetReleaseDate() *time.Time {
	if m != nil {
		return m.ReleaseDate
	}
	return nil
}

func (m *WithdrawPaymentConstraints) GetCw20Payment() []*CW20Payment {
	if m != nil {
		return m.Cw20Payment
	}
	return nil
}

func (m *WithdrawPaymentConstraints) GetCw1155Payment() []*CW1155Payment {
	if m != nil {
		return m.Cw1155Payment
	}
	return nil
}

// CreateClaimAuthorizationAuthorization allows a grantee to create
// SubmitClaimAuthorization and EvaluateClaimAuthorization for specific
// collections(constraints)
type CreateClaimAuthorizationAuthorization struct {
	// address of admin (entity admin module account)
	Admin string `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	// Constraints on the authorizations that can be created
	Constraints []*CreateClaimAuthorizationConstraints `protobuf:"bytes,2,rep,name=constraints,proto3" json:"constraints,omitempty"`
}

func (m *CreateClaimAuthorizationAuthorization) Reset()         { *m = CreateClaimAuthorizationAuthorization{} }
func (m *CreateClaimAuthorizationAuthorization) String() string { return proto.CompactTextString(m) }
func (*CreateClaimAuthorizationAuthorization) ProtoMessage()    {}
func (*CreateClaimAuthorizationAuthorization) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4b7f6c531e101a6, []int{6}
}
func (m *CreateClaimAuthorizationAuthorization) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateClaimAuthorizationAuthorization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateClaimAuthorizationAuthorization.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateClaimAuthorizationAuthorization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClaimAuthorizationAuthorization.Merge(m, src)
}
func (m *CreateClaimAuthorizationAuthorization) XXX_Size() int {
	return m.Size()
}
func (m *CreateClaimAuthorizationAuthorization) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClaimAuthorizationAuthorization.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClaimAuthorizationAuthorization proto.InternalMessageInfo

func (m *CreateClaimAuthorizationAuthorization) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *CreateClaimAuthorizationAuthorization) GetConstraints() []*CreateClaimAuthorizationConstraints {
	if m != nil {
		return m.Constraints
	}
	return nil
}

// CreateClaimAuthorizationConstraints defines the constraints for creating
// claim authorizations
type CreateClaimAuthorizationConstraints struct {
	// Maximum number of authorizations that can be created through this
	// meta-authorization, 0 means no quota
	MaxAuthorizations uint64 `protobuf:"varint,1,opt,name=max_authorizations,json=maxAuthorizations,proto3" json:"max_authorizations,omitempty"`
	// Maximum quota that can be set in created authorizations
	// 0 means no quota maximum quota per authorization
	MaxAgentQuota uint64 `protobuf:"varint,2,opt,name=max_agent_quota,json=maxAgentQuota,proto3" json:"max_agent_quota,omitempty"`
	// Maximum amount that can be set in created authorizations,
	// if empty then any custom amount is allowed in the created authorizations
	// explicitly set to 0 to disallow any custom amount in the created
	// authorizations
	MaxAmount github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=max_amount,json=maxAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"max_amount"`
	// Maximum cw20 payment that can be set in created authorizations,
	// if empty then any cw20 payment is allowed in the created authorizations
	// explicitly set to 0 to disallow any cw20 payment in the created
	// authorizations
	MaxCw20Payment []*CW20Payment `protobuf:"bytes,4,rep,name=max_cw20_payment,json=maxCw20Payment,proto3" json:"max_cw20_payment,omitempty"`
	// Expiration of this meta-authorization(specific constraint), if not set then
	// no expiration
	Expiration *time.Time `protobuf:"bytes,5,opt,name=expiration,proto3,stdtime" json:"expiration,omitempty"`
	// Collection IDs the grantee can create authorizations for, if empty then all
	// collections for the admin are allowed
	CollectionIds []string `protobuf:"bytes,6,rep,name=collection_ids,json=collectionIds,proto3" json:"collection_ids,omitempty"`
	// Types of authorizations the grantee can create (submit, evaluate, or
	// all(both))
	AllowedAuthTypes CreateClaimAuthorizationType `protobuf:"varint,7,opt,name=allowed_auth_types,json=allowedAuthTypes,proto3,enum=ixo.claims.v1beta1.CreateClaimAuthorizationType" json:"allowed_auth_types,omitempty"`
	// Maximum intent duration for the authorization allowed (for submit)
	MaxIntentDurationNs time.Duration `protobuf:"bytes,8,opt,name=max_intent_duration_ns,json=maxIntentDurationNs,proto3,stdduration" json:"max_intent_duration_ns"`
	// Maximum cw1155 payment that can be set in created authorizations,
	// if empty then any cw1155 payment is allowed in the created authorizations
	// explicitly set to amount to 0 to disallow any cw1155 payment in the created
	// authorizations
	MaxCw1155Payment []*CW1155Payment `protobuf:"bytes,9,rep,name=max_cw1155_payment,json=maxCw1155Payment,proto3" json:"max_cw1155_payment,omitempty"`
}

func (m *CreateClaimAuthorizationConstraints) Reset()         { *m = CreateClaimAuthorizationConstraints{} }
func (m *CreateClaimAuthorizationConstraints) String() string { return proto.CompactTextString(m) }
func (*CreateClaimAuthorizationConstraints) ProtoMessage()    {}
func (*CreateClaimAuthorizationConstraints) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4b7f6c531e101a6, []int{7}
}
func (m *CreateClaimAuthorizationConstraints) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateClaimAuthorizationConstraints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateClaimAuthorizationConstraints.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateClaimAuthorizationConstraints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClaimAuthorizationConstraints.Merge(m, src)
}
func (m *CreateClaimAuthorizationConstraints) XXX_Size() int {
	return m.Size()
}
func (m *CreateClaimAuthorizationConstraints) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClaimAuthorizationConstraints.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClaimAuthorizationConstraints proto.InternalMessageInfo

func (m *CreateClaimAuthorizationConstraints) GetMaxAuthorizations() uint64 {
	if m != nil {
		return m.MaxAuthorizations
	}
	return 0
}

func (m *CreateClaimAuthorizationConstraints) GetMaxAgentQuota() uint64 {
	if m != nil {
		return m.MaxAgentQuota
	}
	return 0
}

func (m *CreateClaimAuthorizationConstraints) GetMaxAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.MaxAmount
	}
	return nil
}

func (m *CreateClaimAuthorizationConstraints) GetMaxCw20Payment() []*CW20Payment {
	if m != nil {
		return m.MaxCw20Payment
	}
	return nil
}

func (m *CreateClaimAuthorizationConstraints) GetExpiration() *time.Time {
	if m != nil {
		return m.Expiration
	}
	return nil
}

func (m *CreateClaimAuthorizationConstraints) GetCollectionIds() []string {
	if m != nil {
		return m.CollectionIds
	}
	return nil
}

func (m *CreateClaimAuthorizationConstraints) GetAllowedAuthTypes() CreateClaimAuthorizationType {
	if m != nil {
		return m.AllowedAuthTypes
	}
	return CreateClaimAuthorizationType_ALL
}

func (m *CreateClaimAuthorizationConstraints) GetMaxIntentDurationNs() time.Duration {
	if m != nil {
		return m.MaxIntentDurationNs
	}
	return 0
}

func (m *CreateClaimAuthorizationConstraints) GetMaxCw1155Payment() []*CW1155Payment {
	if m != nil {
		return m.MaxCw1155Payment
	}
	return nil
}

func init() {
	proto.RegisterEnum("ixo.claims.v1beta1.CreateClaimAuthorizationType", CreateClaimAuthorizationType_name, CreateClaimAuthorizationType_value)
	proto.RegisterType((*SubmitClaimAuthorization)(nil), "ixo.claims.v1beta1.SubmitClaimAuthorization")
	proto.RegisterType((*SubmitClaimConstraints)(nil), "ixo.claims.v1beta1.SubmitClaimConstraints")
	proto.RegisterType((*EvaluateClaimAuthorization)(nil), "ixo.claims.v1beta1.EvaluateClaimAuthorization")
	proto.RegisterType((*EvaluateClaimConstraints)(nil), "ixo.claims.v1beta1.EvaluateClaimConstraints")
	proto.RegisterType((*WithdrawPaymentAuthorization)(nil), "ixo.claims.v1beta1.WithdrawPaymentAuthorization")
	proto.RegisterType((*WithdrawPaymentConstraints)(nil), "ixo.claims.v1beta1.WithdrawPaymentConstraints")
	proto.RegisterType((*CreateClaimAuthorizationAuthorization)(nil), "ixo.claims.v1beta1.CreateClaimAuthorizationAuthorization")
	proto.RegisterType((*CreateClaimAuthorizationConstraints)(nil), "ixo.claims.v1beta1.CreateClaimAuthorizationConstraints")
}

func init() { proto.RegisterFile("ixo/claims/v1beta1/authz.proto", fileDescriptor_f4b7f6c531e101a6) }

var fileDescriptor_f4b7f6c531e101a6 = []byte{
	// 1102 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x57, 0x4d, 0x6f, 0x1b, 0x45,
	0x18, 0xce, 0xc6, 0x4e, 0x62, 0xbf, 0x76, 0x52, 0x33, 0x0d, 0x65, 0xe3, 0x46, 0x76, 0x48, 0xd5,
	0x12, 0x55, 0xc4, 0x4e, 0x82, 0xca, 0xe7, 0x05, 0xdb, 0x8d, 0x84, 0xa5, 0xd0, 0x8f, 0x4d, 0xda,
	0x02, 0x42, 0xac, 0xc6, 0xbb, 0x1b, 0x67, 0x88, 0x77, 0xc7, 0xec, 0xcc, 0x26, 0x4e, 0x7f, 0x45,
	0x8f, 0xfc, 0x02, 0x90, 0x7a, 0xe0, 0xc4, 0x85, 0x1b, 0xc7, 0x8a, 0x53, 0x8f, 0x9c, 0x28, 0x4a,
	0x24, 0xae, 0xfc, 0x05, 0x34, 0xb3, 0xb3, 0xf6, 0x3a, 0xde, 0xa0, 0x85, 0x70, 0xe1, 0x94, 0xcc,
	0xfb, 0xf1, 0xbc, 0xcf, 0xcc, 0xfb, 0xbc, 0xb3, 0x63, 0xa8, 0x90, 0x01, 0xad, 0x5b, 0x3d, 0x4c,
	0x5c, 0x56, 0x3f, 0xda, 0xec, 0x38, 0x1c, 0x6f, 0xd6, 0x71, 0xc0, 0x0f, 0x9e, 0xd6, 0xfa, 0x3e,
	0xe5, 0x14, 0x21, 0x32, 0xa0, 0xb5, 0xd0, 0x5f, 0x53, 0xfe, 0xf2, 0x62, 0x97, 0x76, 0xa9, 0x74,
	0xd7, 0xc5, 0x7f, 0x61, 0x64, 0x79, 0xc9, 0xa2, 0xcc, 0xa5, 0xcc, 0x0c, 0x1d, 0xe1, 0x42, 0xb9,
	0xaa, 0x5d, 0x4a, 0xbb, 0x3d, 0xa7, 0x2e, 0x57, 0x9d, 0x60, 0xbf, 0xce, 0x89, 0xeb, 0x30, 0x8e,
	0xdd, 0xbe, 0x0a, 0xa8, 0x84, 0xe1, 0xf5, 0x0e, 0x66, 0xce, 0x90, 0x86, 0x45, 0x89, 0x17, 0x01,
	0x24, 0xb0, 0x54, 0xa4, 0x14, 0xc0, 0xf9, 0x0a, 0x76, 0xe0, 0x63, 0x4e, 0xa8, 0x37, 0x51, 0xc0,
	0x3b, 0x1c, 0x22, 0x88, 0x45, 0xe8, 0x5f, 0xfd, 0x4e, 0x03, 0x7d, 0x37, 0xe8, 0xb8, 0x84, 0xb7,
	0x04, 0x6c, 0x23, 0xe0, 0x07, 0xd4, 0x27, 0x4f, 0x25, 0x04, 0x5a, 0x84, 0x19, 0x6c, 0xbb, 0xc4,
	0xd3, 0xb5, 0x15, 0x6d, 0x2d, 0x6f, 0x84, 0x0b, 0xb4, 0x03, 0x05, 0x8b, 0x7a, 0x8c, 0xfb, 0x98,
	0x78, 0x9c, 0xe9, 0xd3, 0x2b, 0x99, 0xb5, 0xc2, 0xd6, 0xed, 0xda, 0xe4, 0x79, 0xd5, 0x62, 0xc0,
	0xad, 0x51, 0x86, 0x11, 0x4f, 0xff, 0xf0, 0xd6, 0x2f, 0x3f, 0xae, 0xaf, 0xaa, 0x43, 0x0b, 0xcf,
	0x3f, 0xca, 0x1e, 0xe3, 0xb2, 0xfa, 0x53, 0x06, 0xae, 0x25, 0xe3, 0xa1, 0x1b, 0x30, 0x6f, 0xd1,
	0x5e, 0xcf, 0xb1, 0x44, 0xa0, 0x49, 0x6c, 0x45, 0xb7, 0x38, 0x32, 0xb6, 0x6d, 0x54, 0x85, 0x02,
	0xee, 0x3a, 0x1e, 0x37, 0xbf, 0x09, 0x28, 0xc7, 0xfa, 0xf4, 0x8a, 0xb6, 0x96, 0x35, 0x40, 0x9a,
	0x1e, 0x0a, 0x0b, 0xfa, 0x1a, 0xc0, 0xc5, 0x03, 0x13, 0xbb, 0x34, 0xf0, 0xb8, 0x9e, 0x91, 0xbb,
	0x5a, 0xaa, 0x29, 0x66, 0xa2, 0x3f, 0x43, 0x62, 0x2d, 0x4a, 0xbc, 0xe6, 0xc6, 0x8b, 0xdf, 0xaa,
	0x53, 0xcf, 0x5f, 0x55, 0xd7, 0xba, 0x84, 0x1f, 0x04, 0x9d, 0x9a, 0x45, 0x5d, 0xd5, 0x7b, 0xf5,
	0x67, 0x9d, 0xd9, 0x87, 0x75, 0x7e, 0xd2, 0x77, 0x98, 0x4c, 0x60, 0x46, 0xde, 0xc5, 0x83, 0x86,
	0x44, 0x47, 0x6d, 0x28, 0x89, 0x5a, 0xd6, 0xf1, 0xd6, 0x86, 0xd9, 0xc7, 0x27, 0xae, 0xe3, 0x71,
	0x3d, 0x2b, 0x2b, 0x56, 0x93, 0xce, 0xb1, 0xf5, 0x64, 0x6b, 0xe3, 0x41, 0x18, 0x66, 0x2c, 0xb8,
	0x78, 0xd0, 0x3a, 0x1e, 0xae, 0xd1, 0x43, 0x40, 0xc4, 0xe3, 0x62, 0x63, 0x51, 0xe7, 0x4d, 0x8f,
	0xe9, 0x33, 0x2b, 0x9a, 0xa4, 0x1f, 0xaa, 0xa3, 0x16, 0xa9, 0xa3, 0x76, 0x57, 0xc5, 0x34, 0x73,
	0x82, 0xfe, 0xb7, 0xaf, 0xaa, 0x9a, 0x51, 0x0a, 0xd3, 0x23, 0xcf, 0x3d, 0x86, 0xee, 0x03, 0x0a,
	0xd9, 0x6d, 0x6e, 0xde, 0xb9, 0x33, 0xe4, 0x37, 0x2b, 0xf9, 0xbd, 0x99, 0xcc, 0x4f, 0x44, 0x46,
	0x0c, 0x4b, 0x92, 0x61, 0xcc, 0xb2, 0xfa, 0x5c, 0x83, 0xf2, 0xf6, 0x11, 0xee, 0x05, 0x98, 0x3b,
	0xa9, 0x65, 0x76, 0x2f, 0x49, 0x66, 0x6f, 0x27, 0x95, 0x1f, 0x83, 0xbe, 0xb4, 0xd0, 0xfe, 0xcc,
	0x80, 0x7e, 0x11, 0x62, 0x3a, 0xa9, 0x5d, 0x87, 0xbc, 0x64, 0x68, 0x12, 0x3b, 0xe4, 0x9d, 0x37,
	0x72, 0xd2, 0xd0, 0xb6, 0xd9, 0x79, 0x1d, 0x66, 0x26, 0x74, 0xd8, 0x80, 0x42, 0xc7, 0xd9, 0xa7,
	0xbe, 0x63, 0xda, 0x98, 0x3b, 0x7a, 0x56, 0x76, 0xb2, 0x3c, 0xd1, 0xc9, 0xbd, 0xe8, 0x26, 0x69,
	0x66, 0x9f, 0x89, 0x36, 0x42, 0x98, 0x74, 0x17, 0x73, 0x07, 0x1d, 0xc3, 0x6b, 0xb2, 0x81, 0x01,
	0xe3, 0xd4, 0x8d, 0x14, 0x0d, 0xff, 0xbd, 0xa2, 0xaf, 0x88, 0x4e, 0xcb, 0x22, 0x4a, 0xd7, 0x8f,
	0xe1, 0x8d, 0x58, 0xe1, 0x31, 0x79, 0x17, 0xd2, 0xc9, 0x7b, 0x71, 0x08, 0x19, 0x17, 0xf9, 0x97,
	0xb0, 0x34, 0x86, 0x3b, 0x26, 0xcc, 0x62, 0x5a, 0x61, 0x5e, 0x8b, 0x61, 0xc7, 0xe5, 0xf9, 0x83,
	0x06, 0xcb, 0x4f, 0x08, 0x3f, 0xb0, 0x7d, 0x7c, 0xac, 0x6c, 0x69, 0x04, 0xfa, 0x20, 0x49, 0xa0,
	0xb5, 0x24, 0x1a, 0xe7, 0xc0, 0x2f, 0x2d, 0xd1, 0x3f, 0xb2, 0x50, 0xbe, 0x18, 0x13, 0x2d, 0x41,
	0x2e, 0xd2, 0x9f, 0x62, 0x3c, 0xa7, 0xe4, 0x87, 0xde, 0x87, 0x59, 0xe2, 0xf5, 0x83, 0x21, 0xdd,
	0xf2, 0x48, 0x0e, 0xde, 0xe1, 0xb0, 0x5a, 0x5b, 0x84, 0x34, 0xb3, 0x42, 0x0f, 0x86, 0x8a, 0x47,
	0x1f, 0xc1, 0x1c, 0x0d, 0xb8, 0x4c, 0x0d, 0xef, 0xc6, 0xeb, 0x89, 0xa9, 0xf7, 0x65, 0x8c, 0xca,
	0x8d, 0x32, 0x50, 0x13, 0x8a, 0xaa, 0x5b, 0xa6, 0xd0, 0x8f, 0x14, 0xf5, 0x42, 0xb2, 0x18, 0xd4,
	0x7e, 0xf6, 0x4e, 0xfa, 0x8e, 0x51, 0xe8, 0x8f, 0x16, 0xc8, 0x84, 0xd7, 0x2d, 0xea, 0x71, 0x1f,
	0x5b, 0xdc, 0x1c, 0xeb, 0x7f, 0x78, 0xd7, 0xbd, 0x95, 0xd8, 0x7f, 0x95, 0x10, 0xeb, 0x76, 0x73,
	0x5a, 0xd7, 0x8c, 0xab, 0xd6, 0xa4, 0x03, 0x2d, 0x43, 0x9e, 0xd3, 0x86, 0x6d, 0xfb, 0x0e, 0x63,
	0xfa, 0xac, 0x3c, 0xb7, 0x91, 0x01, 0xad, 0x40, 0x61, 0xdf, 0xa7, 0x6e, 0xe4, 0x9f, 0x93, 0xfe,
	0xb8, 0x09, 0xb5, 0xa0, 0xe8, 0x3b, 0x3d, 0x07, 0x33, 0x35, 0xb9, 0xb9, 0x94, 0x93, 0x5b, 0x50,
	0x59, 0x72, 0x74, 0x9b, 0x50, 0x1c, 0x1b, 0x9b, 0x7c, 0xba, 0xb1, 0x29, 0x58, 0xb1, 0x69, 0xf9,
	0x04, 0x16, 0xce, 0x8d, 0x08, 0xa4, 0x1d, 0x91, 0x79, 0x6b, 0x6c, 0x32, 0x7e, 0xd6, 0xe0, 0x66,
	0xcb, 0x77, 0x12, 0xaf, 0xed, 0x34, 0x23, 0xf2, 0x79, 0xd2, 0x88, 0xbc, 0x97, 0x48, 0xe3, 0x82,
	0x2a, 0x97, 0x9e, 0x95, 0xef, 0x67, 0xe0, 0x46, 0x0a, 0x70, 0xb4, 0x1e, 0x7e, 0xf4, 0x70, 0xdc,
	0xcf, 0xe4, 0x6e, 0xb2, 0x86, 0xb8, 0x4d, 0xc7, 0x12, 0x19, 0xba, 0x05, 0x57, 0x64, 0xf8, 0xc4,
	0x93, 0x62, 0x5e, 0xc4, 0xfe, 0xef, 0x5f, 0x15, 0x1f, 0x03, 0x38, 0x83, 0x3e, 0x09, 0x9f, 0x04,
	0x6a, 0xc2, 0x52, 0x7c, 0x83, 0x46, 0x39, 0xe8, 0x26, 0x2c, 0x8c, 0x7d, 0x29, 0x99, 0x7c, 0x40,
	0xe4, 0x8d, 0xf9, 0xf8, 0xa7, 0x92, 0xa1, 0xaf, 0x00, 0xe1, 0x5e, 0x8f, 0x1e, 0x3b, 0xb6, 0x3c,
	0x7a, 0x79, 0x3d, 0x84, 0xd3, 0xb5, 0xb0, 0xb5, 0xf1, 0x4f, 0x84, 0x22, 0x2f, 0x8c, 0x92, 0xc2,
	0x12, 0x1e, 0x61, 0x60, 0xe8, 0x33, 0x10, 0xb7, 0xbe, 0x99, 0xf0, 0x44, 0xca, 0xa5, 0x7f, 0x22,
	0x5d, 0x75, 0xf1, 0xa0, 0x9d, 0xee, 0x95, 0x94, 0xff, 0xd7, 0xaf, 0xa4, 0xdb, 0x0d, 0x58, 0xfe,
	0xbb, 0xcd, 0xa1, 0x39, 0xc8, 0x34, 0x76, 0x76, 0x4a, 0x53, 0x08, 0x60, 0x76, 0xf7, 0x51, 0xf3,
	0xd3, 0xf6, 0x5e, 0x49, 0x43, 0x45, 0xc8, 0x6d, 0x3f, 0x6e, 0xec, 0x3c, 0x6a, 0xec, 0x6d, 0x97,
	0xa6, 0x9b, 0xbb, 0x2f, 0x4e, 0x2b, 0xda, 0xcb, 0xd3, 0x8a, 0xf6, 0xfb, 0x69, 0x45, 0x7b, 0x76,
	0x56, 0x99, 0x7a, 0x79, 0x56, 0x99, 0xfa, 0xf5, 0xac, 0x32, 0xf5, 0xc5, 0x07, 0x31, 0x41, 0x91,
	0x01, 0xdd, 0xa7, 0x81, 0x67, 0x4b, 0x68, 0xb1, 0x5a, 0xef, 0xf4, 0xa8, 0x75, 0x68, 0x1d, 0x60,
	0xe2, 0xd5, 0x8f, 0xde, 0xad, 0x0f, 0xa2, 0x5f, 0x1c, 0xb2, 0x19, 0x9d, 0x59, 0x79, 0x34, 0xef,
	0xfc, 0x15, 0x00, 0x00, 0xff, 0xff, 0xdc, 0xc9, 0x85, 0x81, 0x32, 0x0d, 0x00, 0x00,
}

func (m *SubmitClaimAuthorization) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubmitClaimAuthorization) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubmitClaimAuthorization) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Constraints) > 0 {
		for iNdEx := len(m.Constraints) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Constraints[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuthz(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintAuthz(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SubmitClaimConstraints) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubmitClaimConstraints) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubmitClaimConstraints) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MaxCw1155Payment) > 0 {
		for iNdEx := len(m.MaxCw1155Payment) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MaxCw1155Payment[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuthz(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.IntentDurationNs, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.IntentDurationNs):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintAuthz(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x2a
	if len(m.MaxCw20Payment) > 0 {
		for iNdEx := len(m.MaxCw20Payment) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MaxCw20Payment[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuthz(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.MaxAmount) > 0 {
		for iNdEx := len(m.MaxAmount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MaxAmount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuthz(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.AgentQuota != 0 {
		i = encodeVarintAuthz(dAtA, i, uint64(m.AgentQuota))
		i--
		dAtA[i] = 0x10
	}
	if len(m.CollectionId) > 0 {
		i -= len(m.CollectionId)
		copy(dAtA[i:], m.CollectionId)
		i = encodeVarintAuthz(dAtA, i, uint64(len(m.CollectionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EvaluateClaimAuthorization) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EvaluateClaimAuthorization) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EvaluateClaimAuthorization) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Constraints) > 0 {
		for iNdEx := len(m.Constraints) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Constraints[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuthz(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintAuthz(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EvaluateClaimConstraints) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EvaluateClaimConstraints) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EvaluateClaimConstraints) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MaxCustomCw1155Payment) > 0 {
		for iNdEx := len(m.MaxCustomCw1155Payment) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MaxCustomCw1155Payment[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuthz(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	if len(m.MaxCustomCw20Payment) > 0 {
		for iNdEx := len(m.MaxCustomCw20Payment) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MaxCustomCw20Payment[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuthz(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.MaxCustomAmount) > 0 {
		for iNdEx := len(m.MaxCustomAmount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MaxCustomAmount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuthz(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if m.BeforeDate != nil {
		n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.BeforeDate, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.BeforeDate):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintAuthz(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x22
	}
	if m.AgentQuota != 0 {
		i = encodeVarintAuthz(dAtA, i, uint64(m.AgentQuota))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ClaimIds) > 0 {
		for iNdEx := len(m.ClaimIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ClaimIds[iNdEx])
			copy(dAtA[i:], m.ClaimIds[iNdEx])
			i = encodeVarintAuthz(dAtA, i, uint64(len(m.ClaimIds[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.CollectionId) > 0 {
		i -= len(m.CollectionId)
		copy(dAtA[i:], m.CollectionId)
		i = encodeVarintAuthz(dAtA, i, uint64(len(m.CollectionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *WithdrawPaymentAuthorization) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WithdrawPaymentAuthorization) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WithdrawPaymentAuthorization) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Constraints) > 0 {
		for iNdEx := len(m.Constraints) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Constraints[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuthz(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintAuthz(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *WithdrawPaymentConstraints) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WithdrawPaymentConstraints) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WithdrawPaymentConstraints) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Cw1155Payment) > 0 {
		for iNdEx := len(m.Cw1155Payment) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Cw1155Payment[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuthz(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.Cw20Payment) > 0 {
		for iNdEx := len(m.Cw20Payment) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Cw20Payment[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuthz(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if m.ReleaseDate != nil {
		n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.ReleaseDate, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ReleaseDate):])
		if err3 != nil {
			return 0, err3
		}
		i -= n3
		i = encodeVarintAuthz(dAtA, i, uint64(n3))
		i--
		dAtA[i] = 0x42
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintAuthz(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ToAddress) > 0 {
		i -= len(m.ToAddress)
		copy(dAtA[i:], m.ToAddress)
		i = encodeVarintAuthz(dAtA, i, uint64(len(m.ToAddress)))
		i--
		dAtA[i] = 0x32
	}
	if m.Contract_1155Payment != nil {
		{
			size, err := m.Contract_1155Payment.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAuthz(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.PaymentType != 0 {
		i = encodeVarintAuthz(dAtA, i, uint64(m.PaymentType))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Outputs) > 0 {
		for iNdEx := len(m.Outputs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Outputs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuthz(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Inputs) > 0 {
		for iNdEx := len(m.Inputs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Inputs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuthz(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ClaimId) > 0 {
		i -= len(m.ClaimId)
		copy(dAtA[i:], m.ClaimId)
		i = encodeVarintAuthz(dAtA, i, uint64(len(m.ClaimId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CreateClaimAuthorizationAuthorization) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateClaimAuthorizationAuthorization) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateClaimAuthorizationAuthorization) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Constraints) > 0 {
		for iNdEx := len(m.Constraints) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Constraints[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuthz(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintAuthz(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CreateClaimAuthorizationConstraints) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateClaimAuthorizationConstraints) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateClaimAuthorizationConstraints) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MaxCw1155Payment) > 0 {
		for iNdEx := len(m.MaxCw1155Payment) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MaxCw1155Payment[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuthz(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	n5, err5 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.MaxIntentDurationNs, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxIntentDurationNs):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintAuthz(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x42
	if m.AllowedAuthTypes != 0 {
		i = encodeVarintAuthz(dAtA, i, uint64(m.AllowedAuthTypes))
		i--
		dAtA[i] = 0x38
	}
	if len(m.CollectionIds) > 0 {
		for iNdEx := len(m.CollectionIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.CollectionIds[iNdEx])
			copy(dAtA[i:], m.CollectionIds[iNdEx])
			i = encodeVarintAuthz(dAtA, i, uint64(len(m.CollectionIds[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if m.Expiration != nil {
		n6, err6 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.Expiration, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Expiration):])
		if err6 != nil {
			return 0, err6
		}
		i -= n6
		i = encodeVarintAuthz(dAtA, i, uint64(n6))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.MaxCw20Payment) > 0 {
		for iNdEx := len(m.MaxCw20Payment) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MaxCw20Payment[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuthz(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.MaxAmount) > 0 {
		for iNdEx := len(m.MaxAmount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MaxAmount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuthz(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.MaxAgentQuota != 0 {
		i = encodeVarintAuthz(dAtA, i, uint64(m.MaxAgentQuota))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxAuthorizations != 0 {
		i = encodeVarintAuthz(dAtA, i, uint64(m.MaxAuthorizations))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintAuthz(dAtA []byte, offset int, v uint64) int {
	offset -= sovAuthz(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SubmitClaimAuthorization) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovAuthz(uint64(l))
	}
	if len(m.Constraints) > 0 {
		for _, e := range m.Constraints {
			l = e.Size()
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	return n
}

func (m *SubmitClaimConstraints) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CollectionId)
	if l > 0 {
		n += 1 + l + sovAuthz(uint64(l))
	}
	if m.AgentQuota != 0 {
		n += 1 + sovAuthz(uint64(m.AgentQuota))
	}
	if len(m.MaxAmount) > 0 {
		for _, e := range m.MaxAmount {
			l = e.Size()
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	if len(m.MaxCw20Payment) > 0 {
		for _, e := range m.MaxCw20Payment {
			l = e.Size()
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.IntentDurationNs)
	n += 1 + l + sovAuthz(uint64(l))
	if len(m.MaxCw1155Payment) > 0 {
		for _, e := range m.MaxCw1155Payment {
			l = e.Size()
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	return n
}

func (m *EvaluateClaimAuthorization) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovAuthz(uint64(l))
	}
	if len(m.Constraints) > 0 {
		for _, e := range m.Constraints {
			l = e.Size()
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	return n
}

func (m *EvaluateClaimConstraints) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CollectionId)
	if l > 0 {
		n += 1 + l + sovAuthz(uint64(l))
	}
	if len(m.ClaimIds) > 0 {
		for _, s := range m.ClaimIds {
			l = len(s)
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	if m.AgentQuota != 0 {
		n += 1 + sovAuthz(uint64(m.AgentQuota))
	}
	if m.BeforeDate != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.BeforeDate)
		n += 1 + l + sovAuthz(uint64(l))
	}
	if len(m.MaxCustomAmount) > 0 {
		for _, e := range m.MaxCustomAmount {
			l = e.Size()
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	if len(m.MaxCustomCw20Payment) > 0 {
		for _, e := range m.MaxCustomCw20Payment {
			l = e.Size()
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	if len(m.MaxCustomCw1155Payment) > 0 {
		for _, e := range m.MaxCustomCw1155Payment {
			l = e.Size()
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	return n
}

func (m *WithdrawPaymentAuthorization) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovAuthz(uint64(l))
	}
	if len(m.Constraints) > 0 {
		for _, e := range m.Constraints {
			l = e.Size()
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	return n
}

func (m *WithdrawPaymentConstraints) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClaimId)
	if l > 0 {
		n += 1 + l + sovAuthz(uint64(l))
	}
	if len(m.Inputs) > 0 {
		for _, e := range m.Inputs {
			l = e.Size()
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	if len(m.Outputs) > 0 {
		for _, e := range m.Outputs {
			l = e.Size()
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	if m.PaymentType != 0 {
		n += 1 + sovAuthz(uint64(m.PaymentType))
	}
	if m.Contract_1155Payment != nil {
		l = m.Contract_1155Payment.Size()
		n += 1 + l + sovAuthz(uint64(l))
	}
	l = len(m.ToAddress)
	if l > 0 {
		n += 1 + l + sovAuthz(uint64(l))
	}
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovAuthz(uint64(l))
	}
	if m.ReleaseDate != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ReleaseDate)
		n += 1 + l + sovAuthz(uint64(l))
	}
	if len(m.Cw20Payment) > 0 {
		for _, e := range m.Cw20Payment {
			l = e.Size()
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	if len(m.Cw1155Payment) > 0 {
		for _, e := range m.Cw1155Payment {
			l = e.Size()
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	return n
}

func (m *CreateClaimAuthorizationAuthorization) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovAuthz(uint64(l))
	}
	if len(m.Constraints) > 0 {
		for _, e := range m.Constraints {
			l = e.Size()
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	return n
}

func (m *CreateClaimAuthorizationConstraints) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxAuthorizations != 0 {
		n += 1 + sovAuthz(uint64(m.MaxAuthorizations))
	}
	if m.MaxAgentQuota != 0 {
		n += 1 + sovAuthz(uint64(m.MaxAgentQuota))
	}
	if len(m.MaxAmount) > 0 {
		for _, e := range m.MaxAmount {
			l = e.Size()
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	if len(m.MaxCw20Payment) > 0 {
		for _, e := range m.MaxCw20Payment {
			l = e.Size()
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	if m.Expiration != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Expiration)
		n += 1 + l + sovAuthz(uint64(l))
	}
	if len(m.CollectionIds) > 0 {
		for _, s := range m.CollectionIds {
			l = len(s)
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	if m.AllowedAuthTypes != 0 {
		n += 1 + sovAuthz(uint64(m.AllowedAuthTypes))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxIntentDurationNs)
	n += 1 + l + sovAuthz(uint64(l))
	if len(m.MaxCw1155Payment) > 0 {
		for _, e := range m.MaxCw1155Payment {
			l = e.Size()
			n += 1 + l + sovAuthz(uint64(l))
		}
	}
	return n
}

func sovAuthz(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAuthz(x uint64) (n int) {
	return sovAuthz(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SubmitClaimAuthorization) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthz
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubmitClaimAuthorization: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubmitClaimAuthorization: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Constraints", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Constraints = append(m.Constraints, &SubmitClaimConstraints{})
			if err := m.Constraints[len(m.Constraints)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthz(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthz
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubmitClaimConstraints) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthz
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubmitClaimConstraints: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubmitClaimConstraints: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentQuota", wireType)
			}
			m.AgentQuota = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AgentQuota |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxAmount = append(m.MaxAmount, types.Coin{})
			if err := m.MaxAmount[len(m.MaxAmount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCw20Payment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxCw20Payment = append(m.MaxCw20Payment, &CW20Payment{})
			if err := m.MaxCw20Payment[len(m.MaxCw20Payment)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IntentDurationNs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.IntentDurationNs, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCw1155Payment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxCw1155Payment = append(m.MaxCw1155Payment, &CW1155Payment{})
			if err := m.MaxCw1155Payment[len(m.MaxCw1155Payment)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthz(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthz
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EvaluateClaimAuthorization) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthz
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EvaluateClaimAuthorization: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EvaluateClaimAuthorization: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Constraints", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Constraints = append(m.Constraints, &EvaluateClaimConstraints{})
			if err := m.Constraints[len(m.Constraints)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthz(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthz
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EvaluateClaimConstraints) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthz
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EvaluateClaimConstraints: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EvaluateClaimConstraints: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClaimIds = append(m.ClaimIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentQuota", wireType)
			}
			m.AgentQuota = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AgentQuota |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeforeDate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BeforeDate == nil {
				m.BeforeDate = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.BeforeDate, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCustomAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxCustomAmount = append(m.MaxCustomAmount, types.Coin{})
			if err := m.MaxCustomAmount[len(m.MaxCustomAmount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCustomCw20Payment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxCustomCw20Payment = append(m.MaxCustomCw20Payment, &CW20Payment{})
			if err := m.MaxCustomCw20Payment[len(m.MaxCustomCw20Payment)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCustomCw1155Payment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxCustomCw1155Payment = append(m.MaxCustomCw1155Payment, &CW1155Payment{})
			if err := m.MaxCustomCw1155Payment[len(m.MaxCustomCw1155Payment)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthz(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthz
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WithdrawPaymentAuthorization) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthz
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WithdrawPaymentAuthorization: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WithdrawPaymentAuthorization: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Constraints", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Constraints = append(m.Constraints, &WithdrawPaymentConstraints{})
			if err := m.Constraints[len(m.Constraints)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthz(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthz
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WithdrawPaymentConstraints) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthz
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WithdrawPaymentConstraints: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WithdrawPaymentConstraints: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClaimId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inputs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Inputs = append(m.Inputs, types1.Input{})
			if err := m.Inputs[len(m.Inputs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Outputs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Outputs = append(m.Outputs, types1.Output{})
			if err := m.Outputs[len(m.Outputs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaymentType", wireType)
			}
			m.PaymentType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PaymentType |= PaymentType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contract_1155Payment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Contract_1155Payment == nil {
				m.Contract_1155Payment = &Contract1155Payment{}
			}
			if err := m.Contract_1155Payment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReleaseDate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ReleaseDate == nil {
				m.ReleaseDate = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.ReleaseDate, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cw20Payment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cw20Payment = append(m.Cw20Payment, &CW20Payment{})
			if err := m.Cw20Payment[len(m.Cw20Payment)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cw1155Payment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cw1155Payment = append(m.Cw1155Payment, &CW1155Payment{})
			if err := m.Cw1155Payment[len(m.Cw1155Payment)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthz(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthz
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateClaimAuthorizationAuthorization) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthz
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateClaimAuthorizationAuthorization: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateClaimAuthorizationAuthorization: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Constraints", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Constraints = append(m.Constraints, &CreateClaimAuthorizationConstraints{})
			if err := m.Constraints[len(m.Constraints)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthz(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthz
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateClaimAuthorizationConstraints) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthz
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateClaimAuthorizationConstraints: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateClaimAuthorizationConstraints: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAuthorizations", wireType)
			}
			m.MaxAuthorizations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxAuthorizations |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAgentQuota", wireType)
			}
			m.MaxAgentQuota = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxAgentQuota |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxAmount = append(m.MaxAmount, types.Coin{})
			if err := m.MaxAmount[len(m.MaxAmount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCw20Payment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxCw20Payment = append(m.MaxCw20Payment, &CW20Payment{})
			if err := m.MaxCw20Payment[len(m.MaxCw20Payment)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expiration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Expiration == nil {
				m.Expiration = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.Expiration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollectionIds = append(m.CollectionIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedAuthTypes", wireType)
			}
			m.AllowedAuthTypes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AllowedAuthTypes |= CreateClaimAuthorizationType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxIntentDurationNs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.MaxIntentDurationNs, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCw1155Payment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxCw1155Payment = append(m.MaxCw1155Payment, &CW1155Payment{})
			if err := m.MaxCw1155Payment[len(m.MaxCw1155Payment)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthz(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthz
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAuthz(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAuthz
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAuthz
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAuthz
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAuthz
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAuthz        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAuthz          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAuthz = fmt.Errorf("proto: unexpected end of group")
)
