package types

import (
	errorsmod "cosmossdk.io/errors"
)

const (
	DefaultCodespace = ModuleName
)

var (
	ErrArgumentCannotBeEmpty                = errorsmod.Register(DefaultCodespace, 2, "argument cannot be empty")
	ErrArgumentCannotBeNegative             = errorsmod.Register(DefaultCodespace, 3, "argument cannot be negative")
	ErrArgumentMustBePositive               = errorsmod.Register(DefaultCodespace, 4, "argument must be a positive value")
	ErrArgumentMustBeInteger                = errorsmod.Register(DefaultCodespace, 5, "argument must be an integer value")
	ErrArgumentMustBeBetween                = errorsmod.Register(DefaultCodespace, 6, "argument must be between")
	ErrFunctionParameterMissingOrNonFloat   = errorsmod.Register(DefaultCodespace, 7, "parameter is missing or is not a float")
	ErrArgumentMissingOrNonFloat            = errorsmod.Register(DefaultCodespace, 8, "argument is missing or is not a float")
	ErrArgumentMissingOrNonUInteger         = errorsmod.Register(DefaultCodespace, 9, "argument is missing or is not an unsigned integer")
	ErrArgumentMissingOrNonBoolean          = errorsmod.Register(DefaultCodespace, 10, "argument is missing or is not true or false")
	ErrIncorrectNumberOfReserveTokens       = errorsmod.Register(DefaultCodespace, 11, "incorrect number of reserve tokens")
	ErrIncorrectNumberOfFunctionParameters  = errorsmod.Register(DefaultCodespace, 12, "incorrect number of function parameters")
	ErrBondDoesNotExist                     = errorsmod.Register(DefaultCodespace, 13, "bond does not exist")
	ErrBondAlreadyExists                    = errorsmod.Register(DefaultCodespace, 14, "bond already exists")
	ErrBondTokenIsTaken                     = errorsmod.Register(DefaultCodespace, 15, "bond token is taken")
	ErrBondDoesNotAllowSelling              = errorsmod.Register(DefaultCodespace, 16, "bond does not allow selling at the moment")
	ErrDidNotEditAnything                   = errorsmod.Register(DefaultCodespace, 17, "did not edit any bond field")
	ErrFromAndToCannotBeTheSameToken        = errorsmod.Register(DefaultCodespace, 18, "from and to tokens cannot be the same token")
	ErrDuplicateReserveToken                = errorsmod.Register(DefaultCodespace, 19, "cannot have duplicate tokens in reserve tokens")
	ErrInvalidStateForAction                = errorsmod.Register(DefaultCodespace, 20, "cannot perform that action at the current state")
	ErrUnrecognizedFunctionType             = errorsmod.Register(DefaultCodespace, 21, "unrecognized function type")
	ErrInvalidFunctionParameter             = errorsmod.Register(DefaultCodespace, 22, "invalid function parameter")
	ErrFunctionNotAvailableForFunctionType  = errorsmod.Register(DefaultCodespace, 23, "function is not available for the function type")
	ErrFunctionRequiresNonZeroCurrentSupply = errorsmod.Register(DefaultCodespace, 24, "function requires the current supply to be non zero")
	ErrTokenIsNotAValidReserveToken         = errorsmod.Register(DefaultCodespace, 25, "token is not a valid reserve token")
	ErrMaxSupplyDenomDoesNotMatchTokenDenom = errorsmod.Register(DefaultCodespace, 26, "max supply denom does not match token denom")
	ErrBondTokenCannotAlsoBeReserveToken    = errorsmod.Register(DefaultCodespace, 27, "token cannot also be a reserve token")
	ErrBondTokenCannotBeStakingToken        = errorsmod.Register(DefaultCodespace, 28, "bond token cannot be staking token")
	ErrReserveDenomsMismatch                = errorsmod.Register(DefaultCodespace, 29, "denoms do not match reserve denoms")
	ErrCannotMintMoreThanMaxSupply          = errorsmod.Register(DefaultCodespace, 30, "cannot mint more tokens than the max supply")
	ErrCannotBurnMoreThanSupply             = errorsmod.Register(DefaultCodespace, 31, "cannot burn more tokens than the current supply")
	ErrMaxPriceExceeded                     = errorsmod.Register(DefaultCodespace, 32, "actual prices exceed max prices")
	ErrSwapAmountTooSmallToGiveAnyReturn    = errorsmod.Register(DefaultCodespace, 33, "swap amount too small to give any return")
	ErrSwapAmountCausesReserveDepletion     = errorsmod.Register(DefaultCodespace, 34, "swap amount too large and causes reserve to be depleted")
	ErrOrderQuantityLimitExceeded           = errorsmod.Register(DefaultCodespace, 35, "order quantity limits exceeded")
	ErrValuesViolateSanityRate              = errorsmod.Register(DefaultCodespace, 36, "values violate sanity rate")
	ErrFeesCannotBeOrExceed100Percent       = errorsmod.Register(DefaultCodespace, 37, "sum of fees is or exceeds 100 percent")
	ErrNoBondTokensOwned                    = errorsmod.Register(DefaultCodespace, 38, "no bond tokens of this bond are owned")
	ErrInsufficientReserveToBuy             = errorsmod.Register(DefaultCodespace, 39, "insufficient reserve was supplied to perform buy order")
	ErrBondTokenDoesNotMatchBond            = errorsmod.Register(DefaultCodespace, 40, "bond token does not match bond")
	ErrReservedBondToken                    = errorsmod.Register(DefaultCodespace, 41, "bond token is reserved")
	ErrInvalidAlpha                         = errorsmod.Register(DefaultCodespace, 42, "alpha value is invalid")
	ErrNumericOverflow                      = errorsmod.Register(DefaultCodespace, 43, "numeric overflow")
	ErrInvalidStateProgression              = errorsmod.Register(DefaultCodespace, 44, "invalid state progression requested")
	ErrCannotAllowSellsAndWithdrawals       = errorsmod.Register(DefaultCodespace, 45, "cannot allow both sells and reserve withdrawals")
	ErrInsufficientReserveForWithdraw       = errorsmod.Register(DefaultCodespace, 46, "requested withdraw amount is greater than available reserve")
)
