accounts:
  - name: alice
    coins: [ "1000000000uixo" ]
    mnemonic: clutch script morning bacon knock unique impact update aisle morning okay outer witness liquid ordinary direct mention dove arrow witness speed satisfy work any
    # address: ixo1gp04jgaqvpa5pwndra6a78e05glgllw99k74mm
  - name: bob
    coins: [ "1000000000uixo" ]
    mnemonic: salmon vivid library slow organ flag card check moment venture hip album vehicle write curtain often inquiry bid oven charge catch erosion voice unfold
    # address: ixo1ra5anxz5tpvll3td822ecf7v4aa88at3nd339j
validator:
  name: alice
  staked: "100000000uixo"
faucet:
  name: bob
  coins: [ "100000uixo" ]
  port: 4500
build:
  binary: "ixod1"
host:
  rpc: ":26659"
  p2p: ":26658"
  prof: ":6061"
  grpc: ":9091"
  api: ":1318"
init:
  app:
    minimum-gas-prices: "0.025uixo"
genesis:
  chain_id: "pandora-4.1"
  app_state:
    staking:
      params:
        bond_denom: "uixo"
